# Generated by Django 5.2.4 on 2025-07-08 18:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0002_enhance_crm_models'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='crmactivity',
            new_name='crm_crmacti_account_4f34d3_idx',
            old_name='crm_activity_account_type_idx',
        ),
        migrations.RenameIndex(
            model_name='crmactivity',
            new_name='crm_crmacti_assigne_0a2d2c_idx',
            old_name='crm_activity_assigned_status_idx',
        ),
        migrations.RenameIndex(
            model_name='crmactivity',
            new_name='crm_crmacti_schedul_1f1ab2_idx',
            old_name='crm_activity_scheduled_idx',
        ),
        migrations.RenameIndex(
            model_name='crmcontact',
            new_name='crm_crmcont_account_dab502_idx',
            old_name='crm_contact_account_type_idx',
        ),
        migrations.RenameIndex(
            model_name='crmcontact',
            new_name='crm_crmcont_owner_i_798037_idx',
            old_name='crm_contact_owner_idx',
        ),
        migrations.RenameIndex(
            model_name='crmdeal',
            new_name='crm_crmdeal_account_7268c8_idx',
            old_name='crm_deal_account_stage_idx',
        ),
        migrations.RenameIndex(
            model_name='crmdeal',
            new_name='crm_crmdeal_assigne_7bea82_idx',
            old_name='crm_deal_assigned_idx',
        ),
        migrations.RenameIndex(
            model_name='crmdeal',
            new_name='crm_crmdeal_expecte_500bf0_idx',
            old_name='crm_deal_close_date_idx',
        ),
        migrations.RenameIndex(
            model_name='crmnote',
            new_name='crm_crmnote_account_b0538e_idx',
            old_name='crm_note_account_type_idx',
        ),
        migrations.RenameIndex(
            model_name='crmnote',
            new_name='crm_crmnote_created_7928cd_idx',
            old_name='crm_note_created_by_idx',
        ),
        migrations.RenameIndex(
            model_name='crmtask',
            new_name='crm_crmtask_account_334979_idx',
            old_name='crm_task_account_status_idx',
        ),
        migrations.RenameIndex(
            model_name='crmtask',
            new_name='crm_crmtask_assigne_e8f46e_idx',
            old_name='crm_task_assigned_due_idx',
        ),
        migrations.RenameIndex(
            model_name='crmtask',
            new_name='crm_crmtask_priorit_97f416_idx',
            old_name='crm_task_priority_idx',
        ),
        migrations.RenameIndex(
            model_name='lead',
            new_name='crm_lead_busines_d11d02_idx',
            old_name='crm_lead_business_status_idx',
        ),
        migrations.RenameIndex(
            model_name='lead',
            new_name='crm_lead_lead_so_4ab8ac_idx',
            old_name='crm_lead_source_idx',
        ),
        migrations.RenameIndex(
            model_name='lead',
            new_name='crm_lead_assigne_2d9eb1_idx',
            old_name='crm_lead_assigned_idx',
        ),
        migrations.RenameIndex(
            model_name='lead',
            new_name='crm_lead_lead_sc_6c1609_idx',
            old_name='crm_lead_score_idx',
        ),
    ]
