# Generated by Django 5.2.4 on 2025-07-08 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('businesses', '0002_enhance_business_model'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='businessdocument',
            options={'ordering': ['-created_at'], 'verbose_name': 'Business Document', 'verbose_name_plural': 'Business Documents'},
        ),
        migrations.AlterModelOptions(
            name='businessimage',
            options={'ordering': ['sort_order', '-created_at'], 'verbose_name': 'Business Image', 'verbose_name_plural': 'Business Images'},
        ),
        migrations.AlterModelOptions(
            name='businesslocation',
            options={'ordering': ['-is_primary', 'name'], 'verbose_name': 'Business Location', 'verbose_name_plural': 'Business Locations'},
        ),
        migrations.RenameIndex(
            model_name='business',
            new_name='businesses__verific_3ea0af_idx',
            old_name='businesses_b_verific_8b5c8a_idx',
        ),
        migrations.RenameIndex(
            model_name='business',
            new_name='businesses__is_feat_be1c9d_idx',
            old_name='businesses_b_is_feat_c8b9a1_idx',
        ),
        migrations.RenameIndex(
            model_name='business',
            new_name='businesses__health__43bda1_idx',
            old_name='businesses_b_health__2f4d5e_idx',
        ),
        migrations.RenameIndex(
            model_name='business',
            new_name='businesses__categor_908071_idx',
            old_name='businesses_b_categor_7a8b9c_idx',
        ),
        migrations.RenameIndex(
            model_name='business',
            new_name='businesses__owner_i_7abb69_idx',
            old_name='businesses_b_owner_i_1d2e3f_idx',
        ),
        migrations.RenameIndex(
            model_name='businessanalytics',
            new_name='businesses__busines_b8d479_idx',
            old_name='businesses_b_busines_4g5h6i_idx',
        ),
        migrations.AlterField(
            model_name='businessdocument',
            name='document_type',
            field=models.CharField(choices=[('license', 'Business License'), ('certificate', 'Certificate'), ('registration', 'Registration Document'), ('tax', 'Tax Document'), ('insurance', 'Insurance Document'), ('identity', 'Identity Proof'), ('address', 'Address Proof'), ('other', 'Other')], max_length=20),
        ),
    ]
